
name: 'shopify'
version: '1.0.0'
config-version: 2

profile: 'shopify'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:        
  - "target"
  - "dbt_packages"

models:
  shopify:
      +materialized: view
